apiVersion: v1
kind: Secret
metadata:
  name: system-under-test
  namespace: benk
stringData:
  serviceName: sutServiceName_PLACEHOLDER
  servicePort: "8080"
  backend: sutBackendIP_PLACEHOLDER
  username: sutUsername_PLACEHOLDER
  password: sutPassword_PLACEHOLDER
